spring.application.name=backend
server.port=${PORT:8081}

# Database
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/Hotel_System}
spring.datasource.username=${DB_USERNAME:root}
#spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# File uploads
app.upload.dir=${UPLOAD_DIR:${user.dir}/uploads}

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:yourgmail@gmail.com}
spring.mail.password=${MAIL_PASSWORD:your-app-password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud-name=dlsjifpgx
cloudinary.api-key=341962672135189
cloudinary.api-secret=xUpm5Ratthn5R0a3S0nY76vihTc